name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones repo

      - name: Install Build Tools
        run: sudo apt update && sudo apt install -y g++

      - name: Compile the Calculator
        run: make

      - name: Run the Binary (Optional)
        run: ./calc || echo "Build successful, execution skipped in CI."

      - name: Clean Up Build Files
        run: make clean
